package br.ce.wcaquino.pages;

import static br.ce.wcaquino.core.DriverFactory.getDriver;

import java.util.concurrent.TimeUnit;

import org.junit.Assert;

import br.ce.wcaquino.core.BasePage;

public class PokemonPage41 extends BasePage {

	public void verDetalhes801() throws InterruptedException {
		getDriver().manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("btnMagearna");
		Assert.assertEquals("MAGEARNA", obterTexto("801"));
		getDriver().manage().timeouts().implicitlyWait(0, TimeUnit.SECONDS);

	}
	
	public void verDetalhes802() throws InterruptedException {
		getDriver().manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("btnMarshadow");
		Assert.assertEquals("MARSHADOW", obterTexto("802"));
		getDriver().manage().timeouts().implicitlyWait(0, TimeUnit.SECONDS);

	}
	
	public void verDetalhes803() throws InterruptedException {
		getDriver().manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("btnPoipole");
		Assert.assertEquals("POIPOLE", obterTexto("803"));
		getDriver().manage().timeouts().implicitlyWait(0, TimeUnit.SECONDS);

	}
	
	public void verDetalhes804() throws InterruptedException {
		getDriver().manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("btnNaganadel");
		Assert.assertEquals("NAGANADEL", obterTexto("804"));
		getDriver().manage().timeouts().implicitlyWait(0, TimeUnit.SECONDS);

	}
	
	public void verDetalhes805() throws InterruptedException {
		getDriver().manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("btnStakataka");
		Assert.assertEquals("STAKATAKA", obterTexto("805"));
		getDriver().manage().timeouts().implicitlyWait(0, TimeUnit.SECONDS);

	}
	
	public void verDetalhes806() throws InterruptedException {
		getDriver().manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("btnBlacephalon");
		Assert.assertEquals("BLACEPHALON", obterTexto("806"));
		getDriver().manage().timeouts().implicitlyWait(0, TimeUnit.SECONDS);

	}
	
	public void verDetalhes807() throws InterruptedException {
		getDriver().manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("next");
		clicarBotao("btnZeraora");
		Assert.assertEquals("ZERAORA", obterTexto("807"));
		getDriver().manage().timeouts().implicitlyWait(0, TimeUnit.SECONDS);

	}
	
//	public void verDetalhes808() throws InterruptedException {
//		getDriver().manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("btnDeoxys-attack");
//		Assert.assertEquals("DEOXYS-ATTACK", obterTexto("808"));
//		getDriver().manage().timeouts().implicitlyWait(0, TimeUnit.SECONDS);
//
//	}
//	
//	public void verDetalhes809() throws InterruptedException {
//		getDriver().manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("btnDeoxys-defense");
//		Assert.assertEquals("DEOXYS-DEFENSE", obterTexto("809"));
//		getDriver().manage().timeouts().implicitlyWait(0, TimeUnit.SECONDS);
//
//	}
//	
//	public void verDetalhes810() throws InterruptedException {
//		getDriver().manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("btnCosmoem");
//		Assert.assertEquals("COSMOEM", obterTexto("810"));
//		getDriver().manage().timeouts().implicitlyWait(0, TimeUnit.SECONDS);
//
//	}
//	
//	public void verDetalhes811() throws InterruptedException {
//		getDriver().manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("btnSolgaleo");
//		Assert.assertEquals("SOLGALEO", obterTexto("811"));
//		getDriver().manage().timeouts().implicitlyWait(0, TimeUnit.SECONDS);
//
//	}
//	
//	public void verDetalhes812() throws InterruptedException {
//		getDriver().manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("btnLunala");
//		Assert.assertEquals("LUNALA", obterTexto("812"));
//		getDriver().manage().timeouts().implicitlyWait(0, TimeUnit.SECONDS);
//
//	}
//	
//	public void verDetalhes813() throws InterruptedException {
//		getDriver().manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("btnNihilego");
//		Assert.assertEquals("NIHILEGO", obterTexto("813"));
//		getDriver().manage().timeouts().implicitlyWait(0, TimeUnit.SECONDS);
//
//	}
//	
//	public void verDetalhes814() throws InterruptedException {
//		getDriver().manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("btnBuzzwole");
//		Assert.assertEquals("BUZZWOLE", obterTexto("814"));
//		getDriver().manage().timeouts().implicitlyWait(0, TimeUnit.SECONDS);
//
//	}
//	
//	public void verDetalhes815() throws InterruptedException {
//		getDriver().manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("btnPheromosa");
//		Assert.assertEquals("PHEROMOSA", obterTexto("815"));
//		getDriver().manage().timeouts().implicitlyWait(0, TimeUnit.SECONDS);
//
//	}
//	
//	public void verDetalhes816() throws InterruptedException {
//		getDriver().manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("btnXurkitree");
//		Assert.assertEquals("XURKITREE", obterTexto("816"));
//		getDriver().manage().timeouts().implicitlyWait(0, TimeUnit.SECONDS);
//
//	}
//	
//	public void verDetalhes817() throws InterruptedException {
//		getDriver().manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("btnCelesteela");
//		Assert.assertEquals("CELESTEELA", obterTexto("817"));
//		getDriver().manage().timeouts().implicitlyWait(0, TimeUnit.SECONDS);
//
//	}
//	
//	public void verDetalhes818() throws InterruptedException {
//		getDriver().manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("btnKartana");
//		Assert.assertEquals("KARTANA", obterTexto("818"));
//		getDriver().manage().timeouts().implicitlyWait(0, TimeUnit.SECONDS);
//
//	}
//	
//	public void verDetalhes819() throws InterruptedException {
//		getDriver().manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("btnGuzzlord");
//		Assert.assertEquals("GUZZLORD", obterTexto("819"));
//		getDriver().manage().timeouts().implicitlyWait(0, TimeUnit.SECONDS);
//
//	}
//	
//	public void verDetalhes820() throws InterruptedException {
//		getDriver().manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("next");
//		clicarBotao("btnNecrozma");
//		Assert.assertEquals("NECROZMA", obterTexto("820"));
//		getDriver().manage().timeouts().implicitlyWait(0, TimeUnit.SECONDS);
//
//	}
//
}
